### ISSUE TITLE
Celeba does not extend bob.db.verification.utils.Database

### ISSUE THREAD

**Issue by tiagofrepereira2012** [bioidiap/bob.db.celeba#1]
Hi,

This database doesn't extend `bob.db.verification.utils.Database` so it is not possible to easily reuse on `bob.bio.face`.

**Comment by siebenkopf** [comment]
The database interface does not extend the ``bob.db.verification.utils.Database`` since we do not have the identity information of the images inside the database and, hence, we cannot define an identification protocol.

I have talked to the provider of the database if he could publish the list of identities (which they seem to obtain), but his reply was negative. We **should** implement an identification/verification protocol as soon as the identity labels are available.

**Comment by tiagofrepereira2012** [comment]
My bad, this was written in the README of the package
